/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nocturne;

/**
 *
 * @author Theo
 */
import datapacket.Datapacket;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    private String Filepath = "";

    static void SetPhoto(ImageIcon ResizeImage) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Register() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_genres = new javax.swing.ButtonGroup();
        pnl_Left = new javax.swing.JPanel();
        lbl_password = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        lbl_cfmPassword = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        seperator1 = new javax.swing.JSeparator();
        seperator2 = new javax.swing.JSeparator();
        seperator3 = new javax.swing.JSeparator();
        seperator4 = new javax.swing.JSeparator();
        seperator5 = new javax.swing.JSeparator();
        lbl_username = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_firstName = new javax.swing.JLabel();
        lbl_lastName = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        seperator6 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        txt_cfmPassword = new javax.swing.JPasswordField();
        pnl_Right = new javax.swing.JPanel();
        btn_register = new javax.swing.JButton();
        lbl_profilePic = new javax.swing.JLabel();
        icon_profilePic = new javax.swing.JLabel();
        btn_upload = new javax.swing.JButton();
        lbl_cancel = new javax.swing.JLabel();
        pnl_interests = new javax.swing.JPanel();
        cbx_classical = new javax.swing.JCheckBox();
        cbx_dance = new javax.swing.JCheckBox();
        cbx_hiphop = new javax.swing.JCheckBox();
        cbx_funk = new javax.swing.JCheckBox();
        cbx_folk = new javax.swing.JCheckBox();
        cbx_indie = new javax.swing.JCheckBox();
        cbx_jazz = new javax.swing.JCheckBox();
        cbx_pop = new javax.swing.JCheckBox();
        cbx_soulRandB = new javax.swing.JCheckBox();
        cbx_rock = new javax.swing.JCheckBox();
        cbx_reggae = new javax.swing.JCheckBox();
        cbx_techno = new javax.swing.JCheckBox();
        pnl_toolbar = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 330));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Left.setBackground(new java.awt.Color(7, 51, 73));
        pnl_Left.setPreferredSize(new java.awt.Dimension(300, 300));

        lbl_password.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(57, 113, 177));
        lbl_password.setText("Password:");

        txt_firstName.setBackground(new java.awt.Color(7, 51, 73));
        txt_firstName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_firstName.setForeground(new java.awt.Color(255, 255, 255));
        txt_firstName.setBorder(null);
        txt_firstName.setCaretColor(new java.awt.Color(255, 255, 255));

        lbl_cfmPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_cfmPassword.setForeground(new java.awt.Color(57, 113, 177));
        lbl_cfmPassword.setText("Confirm Password:");

        txt_lastName.setBackground(new java.awt.Color(7, 51, 73));
        txt_lastName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(255, 255, 255));
        txt_lastName.setBorder(null);
        txt_lastName.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lastNameFocusGained(evt);
            }
        });

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(57, 113, 177));
        lbl_username.setText("Username:");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(57, 113, 177));
        lbl_email.setText("Email:");

        lbl_firstName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_firstName.setForeground(new java.awt.Color(57, 113, 177));
        lbl_firstName.setText("First Name:");

        lbl_lastName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_lastName.setForeground(new java.awt.Color(57, 113, 177));
        lbl_lastName.setText("Last Name:");

        txt_email.setBackground(new java.awt.Color(7, 51, 73));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(null);
        txt_email.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
        });

        txt_username.setBackground(new java.awt.Color(7, 51, 73));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(7, 51, 73));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setBorder(null);
        txt_password.setCaretColor(new java.awt.Color(255, 255, 255));

        txt_cfmPassword.setBackground(new java.awt.Color(7, 51, 73));
        txt_cfmPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_cfmPassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_cfmPassword.setBorder(null);
        txt_cfmPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_cfmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cfmPasswordFocusGained(evt);
            }
        });
        txt_cfmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cfmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LeftLayout = new javax.swing.GroupLayout(pnl_Left);
        pnl_Left.setLayout(pnl_LeftLayout);
        pnl_LeftLayout.setHorizontalGroup(
            pnl_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_firstName)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_lastName)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seperator5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cfmPassword)
                    .addComponent(txt_cfmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seperator6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnl_LeftLayout.setVerticalGroup(
            pnl_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LeftLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_firstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_lastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cfmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cfmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnl_Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 420));

        pnl_Right.setBackground(new java.awt.Color(32, 33, 35));
        pnl_Right.setPreferredSize(new java.awt.Dimension(300, 300));

        btn_register.setBackground(new java.awt.Color(57, 113, 177));
        btn_register.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Register");
        btn_register.setPreferredSize(new java.awt.Dimension(250, 25));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        lbl_profilePic.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_profilePic.setForeground(new java.awt.Color(57, 113, 177));
        lbl_profilePic.setText("Profile Picture:");

        icon_profilePic.setBackground(new java.awt.Color(32, 33, 35));
        icon_profilePic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_upload.setBackground(new java.awt.Color(57, 113, 177));
        btn_upload.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_upload.setForeground(new java.awt.Color(255, 255, 255));
        btn_upload.setText("Upload");
        btn_upload.setPreferredSize(new java.awt.Dimension(250, 25));
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        lbl_cancel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_cancel.setForeground(new java.awt.Color(57, 113, 177));
        lbl_cancel.setText("or Cancel");
        lbl_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_cancelMousePressed(evt);
            }
        });

        pnl_interests.setBackground(new java.awt.Color(32, 33, 35));
        pnl_interests.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Select Musical Interests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(57, 113, 177))); // NOI18N

        cbx_classical.setBackground(new java.awt.Color(32, 33, 35));
        cbx_classical.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_classical.setForeground(new java.awt.Color(57, 113, 177));
        cbx_classical.setText("Classical");
        cbx_classical.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_dance.setBackground(new java.awt.Color(32, 33, 35));
        cbx_dance.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_dance.setForeground(new java.awt.Color(57, 113, 177));
        cbx_dance.setText("Dance");
        cbx_dance.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_hiphop.setBackground(new java.awt.Color(32, 33, 35));
        cbx_hiphop.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_hiphop.setForeground(new java.awt.Color(57, 113, 177));
        cbx_hiphop.setText("Hip-Hop");
        cbx_hiphop.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_funk.setBackground(new java.awt.Color(32, 33, 35));
        cbx_funk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_funk.setForeground(new java.awt.Color(57, 113, 177));
        cbx_funk.setText("Funk");
        cbx_funk.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_folk.setBackground(new java.awt.Color(32, 33, 35));
        cbx_folk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_folk.setForeground(new java.awt.Color(57, 113, 177));
        cbx_folk.setText("Folk");
        cbx_folk.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_indie.setBackground(new java.awt.Color(32, 33, 35));
        cbx_indie.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_indie.setForeground(new java.awt.Color(57, 113, 177));
        cbx_indie.setText("Indie");
        cbx_indie.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_jazz.setBackground(new java.awt.Color(32, 33, 35));
        cbx_jazz.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_jazz.setForeground(new java.awt.Color(57, 113, 177));
        cbx_jazz.setText("Jazz");
        cbx_jazz.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_pop.setBackground(new java.awt.Color(32, 33, 35));
        cbx_pop.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_pop.setForeground(new java.awt.Color(57, 113, 177));
        cbx_pop.setText("Pop");
        cbx_pop.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_soulRandB.setBackground(new java.awt.Color(32, 33, 35));
        cbx_soulRandB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_soulRandB.setForeground(new java.awt.Color(57, 113, 177));
        cbx_soulRandB.setText("Soul/R&B");
        cbx_soulRandB.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_rock.setBackground(new java.awt.Color(32, 33, 35));
        cbx_rock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_rock.setForeground(new java.awt.Color(57, 113, 177));
        cbx_rock.setText("Rock");
        cbx_rock.setPreferredSize(new java.awt.Dimension(70, 25));

        cbx_reggae.setBackground(new java.awt.Color(32, 33, 35));
        cbx_reggae.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_reggae.setForeground(new java.awt.Color(57, 113, 177));
        cbx_reggae.setText("Reggae");
        cbx_reggae.setPreferredSize(new java.awt.Dimension(70, 25));
        cbx_reggae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_reggaeActionPerformed(evt);
            }
        });

        cbx_techno.setBackground(new java.awt.Color(32, 33, 35));
        cbx_techno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbx_techno.setForeground(new java.awt.Color(57, 113, 177));
        cbx_techno.setText("Techno");
        cbx_techno.setPreferredSize(new java.awt.Dimension(70, 25));

        javax.swing.GroupLayout pnl_interestsLayout = new javax.swing.GroupLayout(pnl_interests);
        pnl_interests.setLayout(pnl_interestsLayout);
        pnl_interestsLayout.setHorizontalGroup(
            pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_interestsLayout.createSequentialGroup()
                .addGroup(pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_funk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_jazz, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_rock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_interestsLayout.createSequentialGroup()
                        .addComponent(cbx_pop, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_reggae, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_interestsLayout.createSequentialGroup()
                        .addComponent(cbx_soulRandB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_techno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_interestsLayout.createSequentialGroup()
                        .addComponent(cbx_hiphop, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_indie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_interestsLayout.createSequentialGroup()
                .addComponent(cbx_classical, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_dance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_folk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_interestsLayout.setVerticalGroup(
            pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_interestsLayout.createSequentialGroup()
                .addGroup(pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_classical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_dance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_folk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_funk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_indie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_hiphop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_jazz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_pop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_reggae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_interestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_soulRandB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_techno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_rock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_RightLayout = new javax.swing.GroupLayout(pnl_Right);
        pnl_Right.setLayout(pnl_RightLayout);
        pnl_RightLayout.setHorizontalGroup(
            pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RightLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RightLayout.createSequentialGroup()
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_cancel)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RightLayout.createSequentialGroup()
                        .addGroup(pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(icon_profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_RightLayout.createSequentialGroup()
                                .addComponent(lbl_profilePic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(166, 166, 166))))
            .addGroup(pnl_RightLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnl_interests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        pnl_RightLayout.setVerticalGroup(
            pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_profilePic)
                    .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_interests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cancel))
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnl_Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 285, 420));

        pnl_toolbar.setBackground(new java.awt.Color(57, 113, 177));
        pnl_toolbar.setPreferredSize(new java.awt.Dimension(600, 30));
        pnl_toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_toolbarMouseDragged(evt);
            }
        });
        pnl_toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_toolbarMousePressed(evt);
            }
        });

        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nocturne/resources/cancel.png"))); // NOI18N
        lbl_exit.setPreferredSize(new java.awt.Dimension(30, 30));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nocturne/resources/nocturne24.png"))); // NOI18N
        lbl_title.setText("Register To Nocturne");

        javax.swing.GroupLayout pnl_toolbarLayout = new javax.swing.GroupLayout(pnl_toolbar);
        pnl_toolbar.setLayout(pnl_toolbarLayout);
        pnl_toolbarLayout.setHorizontalGroup(
            pnl_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_toolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_toolbarLayout.setVerticalGroup(
            pnl_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_toolbarLayout.createSequentialGroup()
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 585, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx;
    int xy;
    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked

        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void pnl_toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_toolbarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_toolbarMousePressed

    private void pnl_toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_toolbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnl_toolbarMouseDragged

    private void txt_lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameFocusGained

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_cfmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cfmPasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cfmPasswordFocusGained

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void lbl_cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancelMousePressed
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lbl_cancelMousePressed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        Filepath = f.getAbsolutePath();
        icon_profilePic.setIcon(ResizeImage(Filepath));

    }//GEN-LAST:event_btn_uploadActionPerformed

    private void cbx_reggaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_reggaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_reggaeActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Boolean isValid;
        isValid = ValidChecks();

        if (isValid == true) {
            String Password = new String(txt_password.getPassword());
            String PasswordConfirm = new String(txt_cfmPassword.getPassword());
            //If password is entered correctly twice
            if (Password.equals(PasswordConfirm)) {
                ArrayList UserRegister = new ArrayList();

                UserRegister.add(txt_username.getText());
                UserRegister.add(Password);
                UserRegister.add(txt_firstName.getText());
                UserRegister.add(txt_lastName.getText());
                UserRegister.add(txt_email.getText());

                if (cbx_classical.isSelected()) {
                    UserRegister.add("Classical");
                }

                if (cbx_dance.isSelected()) {
                    UserRegister.add("Dance");
                }

                if (cbx_folk.isSelected()) {
                    UserRegister.add("Folk");
                }
                if (cbx_funk.isSelected()) {
                    UserRegister.add("Funk");
                }
                if (cbx_hiphop.isSelected()) {
                    UserRegister.add("HipHop");
                }

                if (cbx_indie.isSelected()) {
                    UserRegister.add("Indie");
                }

                if (cbx_jazz.isSelected()) {
                    UserRegister.add("Jazz");
                }
                if (cbx_pop.isSelected()) {
                    UserRegister.add("Pop");
                }
                if (cbx_reggae.isSelected()) {
                    UserRegister.add("Reggae");
                }
                if (cbx_rock.isSelected()) {
                    UserRegister.add("Rock");
                }
                if (cbx_soulRandB.isSelected()) {
                    UserRegister.add("SoulRandB");
                }
                if (cbx_techno.isSelected()) {
                    UserRegister.add("Techno");
                }

                //Get file path from file chooser               
                try {
                    FileInputStream UserPicture = new FileInputStream(Filepath);
                    byte[] buffer = new byte[UserPicture.available()];
                    UserPicture.read(buffer);

                    Socket NocturneServer = new Socket("localhost", 9090);

                    ObjectOutputStream OutToServer = new ObjectOutputStream(NocturneServer.getOutputStream());
                    ObjectInputStream InFromServer = new ObjectInputStream(NocturneServer.getInputStream());
                    Datapacket UserDetails = new Datapacket();

                    UserDetails.SetCommand("CREATE_USER");
                    UserDetails.SetArray(UserRegister);
                    UserDetails.SetFirstByte(buffer);

                    OutToServer.writeObject(UserDetails);

                    Datapacket Reply = (Datapacket) InFromServer.readObject();
                    OutToServer.close();
                    InFromServer.close();

                    NocturneServer.close();

                    if ("Registered".equals(Reply.GetData())) {
                        ClearForm();

                        JOptionPane.showMessageDialog(this,
                                "Your new account has been created, log in to use Nocturne",
                                "Registering",
                                JOptionPane.PLAIN_MESSAGE);

                        Login login = new Login();
                        login.setLocationRelativeTo(null);
                        login.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "This username belongs to another profile. Please choose another username.",
                                "Registering",
                                JOptionPane.PLAIN_MESSAGE);
                    }

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(this,
                        "Your passwords do not match.",
                        "Error",
                        JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_cfmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cfmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cfmPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_upload;
    private javax.swing.JCheckBox cbx_classical;
    private javax.swing.JCheckBox cbx_dance;
    private javax.swing.JCheckBox cbx_folk;
    private javax.swing.JCheckBox cbx_funk;
    private javax.swing.JCheckBox cbx_hiphop;
    private javax.swing.JCheckBox cbx_indie;
    private javax.swing.JCheckBox cbx_jazz;
    private javax.swing.JCheckBox cbx_pop;
    private javax.swing.JCheckBox cbx_reggae;
    private javax.swing.JCheckBox cbx_rock;
    private javax.swing.JCheckBox cbx_soulRandB;
    private javax.swing.JCheckBox cbx_techno;
    private javax.swing.ButtonGroup group_genres;
    private javax.swing.JLabel icon_profilePic;
    private javax.swing.JLabel lbl_cancel;
    private javax.swing.JLabel lbl_cfmPassword;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_profilePic;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_Left;
    private javax.swing.JPanel pnl_Right;
    private javax.swing.JPanel pnl_interests;
    private javax.swing.JPanel pnl_toolbar;
    private javax.swing.JSeparator seperator1;
    private javax.swing.JSeparator seperator2;
    private javax.swing.JSeparator seperator3;
    private javax.swing.JSeparator seperator4;
    private javax.swing.JSeparator seperator5;
    private javax.swing.JSeparator seperator6;
    private javax.swing.JPasswordField txt_cfmPassword;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(icon_profilePic.getWidth(), icon_profilePic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private Boolean ValidChecks() {

        if (txt_firstName.getText().length() < 2 || txt_lastName.getText().length() < 2) {
            JOptionPane.showMessageDialog(this,
                    "Names need to be at least two characters in length.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);

            return false;
        } else if (txt_email.getText().length() < 5 || txt_username.getText().length() < 5) {
            JOptionPane.showMessageDialog(this,
                    "Email and Usernames need to be a minimum of five characters long.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        } else if (txt_password.getPassword().toString().length() < 6) {
            JOptionPane.showMessageDialog(this,
                    "Passwords should be a minimum of six characters in length.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        } //if email does not contain a "@" or "."
        else if (txt_email.getText().contains("@") == false || txt_email.getText().contains(".") == false) {
            JOptionPane.showMessageDialog(this,
                    "Invalid email format.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }

        int PrefCounter = 0;

        if (cbx_classical.isSelected()) {
            PrefCounter++;
        }

        if (cbx_dance.isSelected()) {
            PrefCounter++;
        }

        if (cbx_folk.isSelected()) {
            PrefCounter++;
        }
        if (cbx_funk.isSelected()) {
            PrefCounter++;
        }
        if (cbx_hiphop.isSelected()) {
            PrefCounter++;
        }

        if (cbx_indie.isSelected()) {
            PrefCounter++;
        }

        if (cbx_jazz.isSelected()) {
            PrefCounter++;
        }
        if (cbx_pop.isSelected()) {
            PrefCounter++;
        }
        if (cbx_reggae.isSelected()) {
            PrefCounter++;
        }
        if (cbx_rock.isSelected()) {
            PrefCounter++;
        }
        if (cbx_soulRandB.isSelected()) {
            PrefCounter++;
        }
        if (cbx_techno.isSelected()) {
            PrefCounter++;
        }

        if (PrefCounter < 1) {
            JOptionPane.showMessageDialog(this,
                    "You need to select at least one Genre.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);

            return false;
        }

        if ("".equals(Filepath)) {
            JOptionPane.showMessageDialog(this,
                    "You need to select a photo.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }

        return true;
    }

    public void ClearForm() {
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_username.setText("");
        txt_email.setText("");
        txt_password.setText("");
        txt_cfmPassword.setText("");

        cbx_classical.setSelected(false);
        cbx_dance.setSelected(false);
        cbx_folk.setSelected(false);
        cbx_funk.setSelected(false);
        cbx_hiphop.setSelected(false);
        cbx_indie.setSelected(false);
        cbx_jazz.setSelected(false);
        cbx_pop.setSelected(false);
        cbx_reggae.setSelected(false);
        cbx_rock.setSelected(false);
        cbx_soulRandB.setSelected(false);
        cbx_techno.setSelected(false);

        icon_profilePic.setIcon(ResizeImage(""));
    }
}
